/*
 *  fluid_advection.h
 *  FluidApp
 *
 */

#ifndef FLUID_ADVECTION_H
#define FLUID_ADVECTION_H

#include "mpx.h"
#include "fluid_cpuCore.h"

//This creates the repos matrix.  It will also do predictor-corrector on
//the advection...
//
//	Note that all streams must be float, same size, and 2-planes.
error *fluidAdvectionGenRepos(	fluidStreamDesc in_vel,		//Velocities
								  fluidStreamDesc out_repos,	//Output repos
								  fluidStreamDesc tmp_vel,		//Temp velocity array
								  fluidStreamDesc tmp_repos,	//Temporary repos
								  float in_timestep,		//The timestep
								  mpTaskSet *in_seq,		//N-CPU helper.
								  int32_t *in_atomic);		//Atomic for n-cpu.

//This executes/replays the repos matrix generated by GenRepos
error *fluidAdvectionAdvect(	fluidStreamDesc in_repos,		//Repos matrix
							   fluidStreamDesc *in_streams,	//Input streams
							   fluidStreamDesc *out_streams,	//Output streams
							   fluidStreamDesc in_coll,		//The collisions!
							   int in_streamCount,			//Number of streams
							   int32_t *in_atomic);			//Atomic for n-cpu

#endif
